[terminal.shell]
program = "/bin/zsh"
args = ["-l", "-c", "tmux"]

[window]
opacity = 0.92
startup_mode = "Maximized"

[font]
size = 12

[font.normal]
family = "MesloLGS NF"

[general]
import = ["~/.config/alacritty/themes/themes/gruvbox_dark.toml"]
